Contact us form captcha
guardian/manage-frontend pull request #518
Opened 2020-11-05 10:13 UTC by rBangay

## What does this change?
Adds a re-captcha gate to the contact us form.

## Images
![Screenshot 2020-11-05 at 10 07 46](https://user-images.githubusercontent.com/2510683/98227622-6d350200-1f4f-11eb-9f99-2e494db58e6f.png)

![Screenshot 2020-11-05 at 10 03 29](https://user-images.githubusercontent.com/2510683/98227670-7aea8780-1f4f-11eb-8cb2-3d4b278ba5e2.png)

2020-11-05 11:33 UTC, ripecosta approved these changes
👍

2020-11-05 13:26 UTC, ripecosta requested changes
The reCaptcha key needs to be submitted with the rest of the form so it can be validated server-side. Otherwise we will be vulnerable to spamming if someone sends messages directly to our endpoint.

2020-11-05 14:21 UTC, rBangay commented
> The reCaptcha key needs to be submitted with the rest of the form so it can be validated server-side. Otherwise we will be vulnerable to spamming if someone sends messages directly to our endpoint.

The form should now pass along the captcha token `captchaToken` along with the rest of the form data

2020-11-05 14:52 UTC, ripecosta requested changes

2020-11-05 14:52 UTC, ripecosta commented on app/server/contactUsApi.ts
> +  body &&
Line 61 already checks `body` so this one is not needed.
```suggestion
```

2020-11-05 14:52 UTC, ripecosta commented on app/server/contactUsApi.ts
> +  body.captchaToken;
The token itself also need to be validated here.

2020-11-06 11:36 UTC, ripecosta requested changes

2020-11-06 11:36 UTC, ripecosta commented on app/server/contactUsApi.ts
> +    const passedCaptchaValidation = await validateCaptchaToken(
At this point in the execution it still hasn't been confirmed that `bodyAsJson.captchaToken` exists. `validateContactUsFormBody` is the validate step of this function, so it makes more sense to validate the captcha inside that function.

2020-11-06 11:36 UTC, ripecosta commented on app/server/contactUsApi.ts
> +  const recaptchaSecret = (await recaptchaConfigPromise)?.secretKey;
Can we fail the check before making the validation fetch if `recaptchaSecret` is undefined?

2020-11-06 11:36 UTC, ripecosta commented on app/server/recaptchaConfig.ts
> +export const recaptchaConfigPromise = s3ConfigPromise<ReCaptchaKeys>()(
Should we log an error in Sentry if the promise comes back with 'undefined'?

2020-11-09 11:57 UTC, ripecosta approved these changes
👍

2020-11-09 12:19 UTC, merged