Help centre landing page
guardian/manage-frontend pull request #539
Opened 2020-11-27 10:36 UTC by rBangay

## What does this change?
Create a MVP of the help centre landing page on a new public url `/help-center/`. (not currently linked to from anywhere).

Content is driven from local config file.

Makes use of the following contact-us page furniture pr https://github.com/guardian/manage-frontend/pull/537

## Images
![Screenshot_2020-11-27 My Account The Guardian](https://user-images.githubusercontent.com/2510683/100440162-5e4bf600-309c-11eb-9842-aa7b8ea48918.png)

2020-11-27 13:45 UTC, kelvin-chappell commented on app/client/components/helpCentre/helpCentreConfig.ts
> +        title: "What payment methods you accept?",
```suggestion
        title: "What payment methods do you accept?",
```

2020-11-27 13:45 UTC, kelvin-chappell commented on app/client/components/helpCentre/helpCentreConfig.ts
> +        title: "Why am I still seeings ads/banners?",
```suggestion
        title: "Why am I still seeing ads/banners?",
```

2020-11-27 15:55 UTC, kelvin-chappell submitted a review, later dismissed
👍

2020-11-30 12:18 UTC, ripecosta commented on app/client/components/helpCentre/HelpTopicBox.tsx
> +        border: 1px solid ${palette.neutral["86"]};
Can we move these big chunks of CSS into their own variables to make it easier to read what this component returns?

2020-11-30 14:26 UTC, ripecosta requested changes
Left a few comments. Happy to approve once the CSS comments are addressed.

2020-11-30 14:26 UTC, ripecosta commented on app/shared/requiresSignin.ts
>  // To avoid security vulnerabilities do no add public paths that do not end in a slash
While we're here...

```suggestion
// To avoid security vulnerabilities do not add public paths that do not end in a slash
```

2020-11-30 14:26 UTC, ripecosta commented on app/client/components/helpCentre/helpCentre.tsx
> +          css={css`
Same thing here. Can we any CSS chunk that has 3 or more lines of code into their own variables to make it easier to read what this component returns?

2020-11-30 16:45 UTC, rBangay commented on app/client/components/helpCentre/helpCentreConfig.ts
> +  links: Array<{ title: string; link: string }>;
I'll add the id's for in the links in with the subsequent analytics card/pr

2020-11-30 17:56 UTC, rBangay commented on app/client/components/helpCentre/HelpTopicBox.tsx
> +            key={`${props.topic.id}Question-${questionIndex}`}
This can be changed to use the tracking id for the links as part of the subsequent analytics card/pr

2020-12-01 09:49 UTC, ripecosta approved these changes
Do the thing!
👍

2020-12-01 09:58 UTC, merged